version: "3"

services:
  db:
    container_name: hw12_postgres
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mzPk2EJJP
    ports:
      - '5432:5432'
    volumes:
      - dbstorage:/var/lib/postgresql/data
      - ../migrations/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  dbstorage:
    driver: local