CREATE TABLE "public"."events" (
   "ID" int8 generated by default as identity,
   "Title" text COLLATE "pg_catalog"."default" not null,
   "DateStart" timestamp(6) not null,
   "DateEnd" timestamp(6) not null,
   "Description" text COLLATE "pg_catalog"."default",
   "UserID" int8,
   "NotificationInterval" int4
);